language: julia
os:
  - linux
  - osx
julia:
  - "1.0"
  - "1.1"
  - "nightly"
env:
  - PYTHON=   # Always use Conda
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  # Apparently the asdf.py package needs jsonschema>=2.3<=2.6, but
  # sometimes jsonschema 3.0.1 will be installed. I assume that
  # someone should fix the "asdf.py" package instead...
  - julia -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.list(); Conda.add("jsonschema>=2.3,<=2.6"); Conda.list()'
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ASDF")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#  - julia -e 'using Pkg; cd(Pkg.dir("ASDF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
