environment:
  matrix:
    - julia_version: "1.0"
    - julia_version: "1.1"
    - julia_version: "nightly"

platform:
  - x86                         # 32-bit
  - x64                         # 64-bit

matrix:
  allow_failures:
    - julia_version: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  # Apparently the asdf.py package needs jsonschema>=2.3<=2.6, but
  # sometimes jsonschema 3.0.1 will be installed. I assume that
  # someone should fix the "asdf.py" package instead...
  # TODO: How does one quote quotes here?
  - C:\julia\bin\julia -e "using Pkg; Pkg.add(String(['C','o','n','d','a'])); using Conda; Conda.list(); Conda.add(String(['j','s','o','n','s','c','h','e','m','a','>','=','2','.','3',',','<','=','2','.','6'])); Conda.list()"
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"

# # Uncomment to support code coverage upload. Should only be enabled for packages
# # which would have coverage gaps without running on Windows
# on_success:
#   - echo "%JL_CODECOV_SCRIPT%"
#   - C:\julia\bin\julia -e "%JL_CODECOV_SCRIPT%"
